version: "3.9"
services:
  web:
    build: .
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ".:/var/www/html"
    environment:
      APP_ENV: "dev"
  db:
    image: "mysql:5.7-debian"
    environment:
      MYSQL_USER: swa
      MYSQL_PASSWORD: swa
      MYSQL_DATABASE: swa
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
