name: "Build & Publish Container"
on:
  push:
    branches:
      - master
    paths:
      - 'composer.json'
      - 'composer.lock'
      - 'Dockerfile'
      - 'package-lock.json'
      - 'package.json'
  workflow_dispatch:
permissions:
  packages: write
  contents: read
jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/wooky/simplewebapps:latest
